### PR TITLE
Add gfortran version 12 and remove 9 and 10.

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

I added myself as a maintainer to go with gfortran_impl_osx-64-feedstock.

### CODE REVIEW

**Comment by erykoff** [comment]
@isuruf At this point I don't understand what is going wrong with the `linux_64_cross_target` builds, or even how this is supposed to work or which direction they're supposed to go.  Hopefully I didn't mess something up with `gfortran_impl`?

**Comment by beckermr** [comment]
What does `-dumpspecs` show for the compilers? That looks like it might be empty or something?

I'm just guessing here...

**Comment by erykoff** [comment]
I don't know what that means.

**Comment by beckermr** [comment]
Oh I just mean we can add `gcc -dumpspecs` in the CI job bash script and see what gives? 

The code says the specfile is missing and I am curious if this might help us find more info on that?

**Comment by erykoff** [comment]
This is in the tests, not the build, right?  I am basically confused about what it's supposed to be doing... I guess this is building on macos to target linux?

**Comment by beckermr** [comment]
Something like that. I always forget host vs target vs build vs whatever here.

**Comment by erykoff** [comment]
Okay, in #48 which I did basically nothing it's the same failures and even for 9.5 which wasn't touched by the recent PR.  And I also note that the impl package for the linux cross build seems to be coming from ctng feedstock, and not from the gfortran_impl_osx feedstock.  Is this even something that we're supposed to be building?  Is it used by anything?

**Comment by beckermr** [comment]
Which package comes from ctng?

**Comment by beckermr** [comment]
This warning is likely unrelated but not ideal:

```
The install/build script(s) for gfortran_osx-64 deleted the following files (from dependencies) from the prefix:
['x86_64-conda-linux-gnu/lib/libgfortran.so', 'x86_64-conda-linux-gnu/lib/libgfortran.so.5', 'x86_64-conda-linux-gnu/lib/libgfortran.so.5.0.0']
This will cause the post-link checks to mis-report. Please try not to delete and files (DSOs in particular) from the prefix
WARNING:conda_build.build:The install/build script(s) for gfortran_osx-64 deleted the following files (from dependencies) from the prefix:
['x86_64-conda-linux-gnu/lib/libgfortran.so', 'x86_64-conda-linux-gnu/lib/libgfortran.so.5', 'x86_64-conda-linux-gnu/lib/libgfortran.so.5.0.0']
This will cause the post-link checks to mis-report. Please try not to delete and files (DSOs in particular) from the prefix
number of files: 9
```

**Comment by beckermr** [comment]
FWIW, this bug must be in the upstream compiler builds, not here. This package is a simple wrapper to set env vars and such.

**Comment by erykoff** [comment]
So in the build log you see this being installed:
```
    gfortran_impl_linux-64:   12.2.0-h55be85b_19        conda-forge
```
And that build (19) is from https://github.com/conda-forge/ctng-compilers-feedstock/blob/main/recipe/meta.yaml (and also according to the conda forge package searcher thingy).

**Comment by beckermr** [comment]
Ohhh that's fine. We never made a new feedstock but ctng is not used there. We build from the upstream source.

**Comment by erykoff** [comment]
Okay, I'm at a loss as to how this ever worked.  The problem as far as I can tell is that running gfortran needs `$PREFIX/lib/libgfortran.spec` to be there.  And this is installed explicitly in the `gfortran_impl_osx-64` installation of `gfortran_impl_{{ cross_target_platform }}` here: https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/blob/main/recipe/meta.yaml#L163

But for the `linux-64` version this gets all messed up.  Because `gfortran_impl_linux-64` is defined as an output of _both_ `gfortran_impl_osx-64-feedstock` and `ctng-compilers-feedstock`.  And the `ctng-compilers-feedstock` does not seem to install `$PREFIX/lib/libgfortran.spec`.  And I don't know what the conda forge system is supposed to do when two feedstocks define the same output package (this seems bad!) but right now it ends up finding the one from `ctng-compilers-feedstock` which doesn't have the spec file in the right location.

I think this is a bigger problem than I know how to solve, or even what the solution is supposed to look like.

I also don't know why we're building these linux packages in osx-64 land anyway.

**Comment by beckermr** [comment]
The packages are for cross compiling builds. I agree we don't usually use them but they are built. It seems to me that the solution is to put the spec file in the right spot in ctng compilers.

**Comment by erykoff** [comment]
Isn't it a problem that two different feedstocks are producing packages with the same name?

**Comment by beckermr** [comment]
That's not necessarily an issue as long as the builds are compatible.

**Comment by erykoff** [comment]
Okay, so more digging, and I may be wrong.  The tests are run on linux, and are installing `gfortran_impl_osx-64`.  Which when installed on macos has `lib/libgfortran.spec` (as a symlink).  But when installed on `linux` it doesn't?  I'm guessing something is being stripped, and maybe this is a new feature of conda?  (Because this ran in august 2022, but not today, so what else would have changed?).

**Comment by beckermr** [comment]
Idk.

**Comment by erykoff** [comment]
@isuruf @beckermr I've done further digging and there just seems to be some strange incompatibility with our linux gfortran build and the osx gfortran build that is triggering what seems to be a bug in gcc (that it tries to read a directory as a spec file in some instances when it's scanning?).  This is currently the case for any existing installation; I'm not sure how/if it ever worked.  Obviously the ability of cross compiling fortran code from linux to osx-64 or osx-arm64 isn't something that people have been making much use of (or else there would be complaints) so I've turned it off on this PR.

Please let me know if there are any problems with this.

**Comment by isuruf** [comment]
I do use the linux-64 to osx-64/osx-arm64 cross compiling and the current environment I have has `gfortran_impl_osx-arm64   11.3.0  he99ca6a_27` in it and it works. `*_28` and  `*_29` does not work anymore. I'll have a look soon

**Comment by erykoff** [comment]
Interesting.  27 to 28 was this PR https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/pull/64/files which added what looks like an unrelated patch.  But the c compiler versions were updated, and then the cross-run test had to be removed (!!) https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/blob/main/recipe/gfortran_test.sh#L5-L6 which looks like the same problem we're having here.  Very curious.

**Comment by beckermr** [comment]
We should mark any broken packages as such. @isuruf @erykoff I'm happy to make the PR but IDK which ones exactly we need to remove.

**Comment by erykoff** [comment]
The other notable thing is that in the 27 build (this is `linux_64/gfortran_impl_osx-64-11.3.0-hacec75c_27` which works) then the `lib/` directory only has `gcc` but in the 28 build (`linux_64/gfortran_impl_osx-64-11.3.0-h7451c75_28`) and the 29 build (`linux_64/gfortran_impl_osx-64-11.3.0-h1f927f5_29`) then the `lib/` directory has the `libgfortran.a`, `libgomp.a`, and the links to `libgfortran.spec` and `libgomp.spec`.  Maybe these aren't supposed to be there for the cross-packages?  Though I don't see what changed to put them there.

I assume the same problems for the other non-11.3.0 versions with those builds.

**Comment by isuruf** [comment]
https://github.com/gcc-mirror/gcc/blob/master/gcc/gcc.cc#L8334-L8335 seems to not strcat specs in there whereas `*_27` does

**Comment by isuruf** [comment]
Looks like an issue with conda binary prefix modification. Installing the compiler into a prefix with exactly 255 characters works.

**Comment by isuruf** [comment]
Marking https://github.com/gcc-mirror/gcc/blob/553ff2524f412be4e02e2ffb1a0a3dc3e2280742/gcc/gcc.cc#L1617-L1620 as volatile should probably fix it

**Comment by erykoff** [comment]
@isuruf Thanks to your fix at https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/pull/69 this now builds and passes tests on all platforms.  Thanks so much for your help figuring out what was going wrong!

**Comment by beckermr** [comment]
I'm going to merge this at the end of the day if I do not hear anything else.

**Pull request merged**
