### PR TITLE
Only report env diff in conda-build

### PR DESCRIPTION
**Pull request by xhochy**
Took the code from `ctng-compiler-activation`

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
We should fix the license while we are here. and it needs a rerender

**Comment by xhochy** [comment]
It has a rerender.

**Comment by xhochy** [comment]
All fixed and CI passed.

**Comment by beckermr** [comment]
Thank you!

**Pull request merged**
